FROM node:latest

MAINTAINER Jakob von der Haar

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY offline_dl/package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY ./offline_dl /usr/src/app

# Expose port
EXPOSE 3000

CMD [ "node", "index.js" ]